
import {
  LayoutDashboard,
  PenTool,
  Eraser,
  Image as ImageIcon,
  Film,
  Maximize2,
  Mic,
  Layers,
  Wand2,
  Code2,
  Cpu,
  Workflow,
  Terminal,
  Globe,
  Sparkles,
  Settings,
  LogOut,
  Download,
  Share2,
  Play,
  Pause,
  Volume2,
  ArrowRight,
  Upload,
  AlertCircle,
  ExternalLink,
  Hexagon,
  Grid,
  Crop,
  Sliders,
  Palette,
  Clapperboard,
  MonitorUp,
  Gamepad2,
  Wand,
  Zap,
  Monitor,
  Search,
  Filter,
  Check,
  Info,
  Shield,
  Users,
  Activity,
  Server,
  Database,
  FileText,
  Lock,
  Github,
  Box,
  Cloud,
  Wallet,
  Key,
  Factory,
  Pickaxe,
  Container,
  ListVideo,
  Thermometer,
  Brain,
  GitBranch,
  Target,
  FlaskConical,
  Dna,
  Microscope,
  BoxSelect,
  Bitcoin,
  Gem,
  Layers as LayerGroup,
  Network,
  Fingerprint,
  Gauge,
  History,
  Power,
  Headphones, // New icon for Music Generator
  ChevronDown, // New: for expand/collapse
  ChevronRight, // New: for expand/collapse
  Plus,
  Minus,
  MousePointer2,
  MoreHorizontal
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Sketch: PenTool,
  Erase: Eraser,
  Image: ImageIcon,
  Video: Film,
  Upscale: Maximize2,
  Maximize2: Maximize2, // Exposed for direct access
  Voice: Mic,
  Layers: Layers,
  Magic: Wand2,
  Wand2: Wand2, // Exposed for direct access
  Code: Code2,
  Chip: Cpu,
  Cpu: Cpu, // Exposed for direct access
  Workflow: Workflow,
  Terminal: Terminal,
  Browser: Globe,
  Globe: Globe,
  Sparkles: Sparkles,
  Settings: Settings,
  Logout: LogOut,
  Download: Download,
  Share: Share2,
  Play: Play,
  Pause: Pause,
  Volume: Volume2,
  ArrowRight: ArrowRight,
  Upload: Upload,
  Alert: AlertCircle,
  Link: ExternalLink,
  Logo: Hexagon,
  Hexagon: Hexagon,
  Grid: Grid,
  Crop: Crop,
  Sliders: Sliders,
  Palette: Palette,
  Clapperboard: Clapperboard,
  MonitorUp: MonitorUp,
  Gamepad: Gamepad2,
  Wand: Wand,
  Zap: Zap,
  Monitor: Monitor,
  UHD: Monitor,
  Search: Search,
  Filter: Filter,
  Check: Check,
  Info: Info,
  Shield: Shield,
  Users: Users,
  Activity: Activity,
  Server: Server,
  Database: Database,
  File: FileText,
  Lock: Lock,
  Github: Github,
  Box: Box,
  Cloud: Cloud,
  Wallet: Wallet,
  Key: Key,
  Factory: Factory,
  Pickaxe: Pickaxe,
  Container: Container,
  ListVideo: ListVideo,
  Thermometer: Thermometer,
  Brain: Brain,
  GitBranch: GitBranch,
  Target: Target,
  FlaskConical: FlaskConical,
  Dna: Dna,
  Microscope: Microscope,
  Selection: BoxSelect,
  Crypto: Bitcoin,
  Gem: Gem,
  LayerGroup: LayerGroup,
  Network: Network,
  Fingerprint: Fingerprint,
  Gauge: Gauge, // Reusing Gauge for Prometheus
  History: History,
  Power: Power,
  Headphones: Headphones, // Added for Music Generator
  ChevronDown: ChevronDown, // Added for expand/collapse
  ChevronRight: ChevronRight, // Added for expand/collapse
  Plus: Plus,
  Minus: Minus,
  MousePointer2: MousePointer2,
  MoreHorizontal: MoreHorizontal
};
